Added support for SMTP authentication
bitnami/bitnami-docker-mediawiki pull request #98
Opened 2021-06-18 14:11 UTC by rednevals

**Description of the change**
This change enables configuration of the SMTP authentication setting. Currently this setting is hard coded to '**true**'.

Both the configuration and validation code were updated, as well as the README.

**Benefits**
In some cases the target SMTP server may not support authentication. Now you will be able to configure authentication to '**false**'. In this mode, the values of username and password will not be used when creating LocalSettings.php.

2021-06-18 16:10 UTC, marcosbc requested changes
Thanks for the PR! It's a great suggestion. I've added some requests mainly to improve the legibility and also be consistent with the approach we are following with other Bitnami solutions.

2021-06-18 16:10 UTC, marcosbc commented on 1/debian-10/rootfs/opt/bitnami/scripts/libmediawiki.sh
> +        is_empty_value "$MEDIAWIKI_SMTP_AUTH" && warn "The MEDIAWIKI_SMTP_AUTH environment variable is empty or not set."
Since it is a boolean value, instead of including its raw value, we could try this:

```suggestion
        check_yes_no_value "MEDIAWIKI_ENABLE_SMTP_AUTH"
```

2021-06-18 16:10 UTC, marcosbc commented on 1/debian-10/rootfs/opt/bitnami/scripts/libmediawiki.sh
> +EOF
If the default values for username/password are empty, does it make sense to add this if condition? Won't MediaWiki be able to know not to use the username/pass if `auth` is `true`?

2021-06-18 16:10 UTC, marcosbc commented on 1/debian-10/rootfs/opt/bitnami/scripts/libmediawiki.sh
> +'auth' => ${MEDIAWIKI_SMTP_AUTH}
In accordance with my above suggestion:

```suggestion
'auth' => $(php_convert_to_boolean "$MEDIAWIKI_ENABLE_SMTP_AUTH")
```

2021-06-18 16:10 UTC, marcosbc commented on 1/debian-10/rootfs/opt/bitnami/scripts/mediawiki-env.sh
> +export MEDIAWIKI_SMTP_AUTH="${MEDIAWIKI_SMTP_AUTH:-}" # only used during the first initialization
In accordance with my above suggestion:

```suggestion
MEDIAWIKI_SMTP_AUTH="${MEDIAWIKI_ENABLE_SMTP_AUTH:-"${SMTP_AUTH:-}"}"
export MEDIAWIKI_SMTP_AUTH="${MEDIAWIKI_ENABLE_SMTP_AUTH:-}" # only used during the first initialization
```

2021-06-18 16:10 UTC, marcosbc commented on README.md
> +- `MEDIAWIKI_SMTP_AUTH`: SMTP account authentication (true or false).
In accordance with my above suggestion:

```suggestion
- `MEDIAWIKI_ENABLE_SMTP_AUTH`: SMTP account authentication (true or false).
```

2021-06-18 17:35 UTC, rednevals commented on 1/debian-10/rootfs/opt/bitnami/scripts/libmediawiki.sh
> +        is_empty_value "$MEDIAWIKI_SMTP_AUTH" && warn "The MEDIAWIKI_SMTP_AUTH environment variable is empty or not set."
The expected value is boolean. But, **check_yes_no_value** is trying to enforce yes/no. Are you suggesting that MEDIAWIKI_ENABLE_SMTP_AUTH should be yes/no, causing us to convert to boolean when writing the settings file? 

Are we trying to enforce that this always be defined?

2021-06-18 17:35 UTC, rednevals commented on 1/debian-10/rootfs/opt/bitnami/scripts/libmediawiki.sh
> +EOF
I think you are correct, they would be ignored It would not hurt for them to be defined.

2021-06-18 17:39 UTC, marcosbc commented on 1/debian-10/rootfs/opt/bitnami/scripts/libmediawiki.sh
> +        is_empty_value "$MEDIAWIKI_SMTP_AUTH" && warn "The MEDIAWIKI_SMTP_AUTH environment variable is empty or not set."
Yes, I think it makes sense to add a default value (`no`). Note that `check_yes_no_value` not only allows for `yes`/`no` but also `true`/`false`.

2021-06-18 18:00 UTC, rednevals commented
Please see latest commit. With the following docker-compose.yml setup:

```   
    - MEDIAWIKI_SMTP_HOST=<smtp host>
    - MEDIAWIKI_SMTP_HOST_ID=<smtp domain>
    - MEDIAWIKI_SMTP_PORT=25
    - MEDIAWIKI_ENABLE_SMTP_AUTH=yes
```
Resulting configuration:
```# Configure SMTP server
$wgSMTP = array(
'host' => '<smtp host>',
'IDHost' => '<smtp domain>',
'port' => 25,
'username' => '',
'password' => '',
'auth' => true
);
```

2021-06-18 18:14 UTC, rednevals commented
It appears that MediaWiki still is making use of the username/password. I will verify:

**Mailer returned: authentication failure [SMTP: SMTP server does not support authentication**

2021-06-18 18:47 UTC, rednevals commented on 1/debian-10/rootfs/opt/bitnami/scripts/libmediawiki.sh
> +        is_empty_value "$MEDIAWIKI_SMTP_AUTH" && warn "The MEDIAWIKI_SMTP_AUTH environment variable is empty or not set."
I see, but the error would print that only yes/no are valid:

```
check_yes_no_value() {
    if ! is_yes_no_value "${!1}" && ! is_true_false_value "${!1}"; then
        print_validation_error "The allowed values for ${1} are: yes no"
    fi
}
```

Anyway, the latest changes should work...

2021-06-18 19:03 UTC, rednevals commented on 1/debian-10/rootfs/opt/bitnami/scripts/libmediawiki.sh
> +        is_empty_value "$MEDIAWIKI_SMTP_AUTH" && warn "The MEDIAWIKI_SMTP_AUTH environment variable is empty or not set."
Should we add a default value in Dockerfile?

```
...
MEDIAWIKI_ENABLE_SMTP_AUTH="no" \
...
```

2021-06-21 12:53 UTC, marcosbc requested changes
It looks a lot better now, thanks! I'm requesting some last simple changes in order to avoid possible issues when upgrading from previous deployments.

2021-06-21 12:53 UTC, marcosbc commented on 1/debian-10/Dockerfile
> +    SMTP_ENABLE_AUTH="no" \
Actually no default is needed in the Dockerfile. We are trying to avoid that. Instead, specifying the default value in `mediawiki-env.sh` should be enough (I'll share a snippet for that below).

 ```suggestion
```

2021-06-21 12:53 UTC, marcosbc commented on 1/debian-10/rootfs/opt/bitnami/scripts/mediawiki-env.sh
> +export MEDIAWIKI_ENABLE_SMTP_AUTH="${MEDIAWIKI_ENABLE_SMTP_AUTH:-}" # only used during the first initialization
Adding a default value:
```suggestion
export MEDIAWIKI_ENABLE_SMTP_AUTH="${MEDIAWIKI_ENABLE_SMTP_AUTH:-yes}" # only used during the first initialization
```


I believe `yes` should be a default value because it used to be the previous hardcoded value. If not, users wanting to enable SMTP auth after upgrading will be forced to declare the new envvar in their docker-compose/deployment.

2021-06-21 12:58 UTC, marcosbc approved these changes
LGTM! Thanks a lot!

2021-06-21 13:23 UTC, merged